# Generated by Django 3.0.8 on 2020-07-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='song',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('artist', models.CharField(max_length=80)),
                ('song_file', models.FileField(upload_to='static/songs/')),
            ],
        ),
    ]
